# Generated by Django 2.1.7 on 2019-04-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemPrice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruberpriceitem',
            old_name='date',
            new_name='ruber_date',
        ),
        migrations.RenameField(
            model_name='ruberpriceitem',
            old_name='name',
            new_name='ruber_name',
        ),
        migrations.RenameField(
            model_name='ruberpriceitem',
            old_name='prrice',
            new_name='ruber_prrice',
        ),
    ]
