# Generated by Django 2.1.7 on 2019-04-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemPrice', '0002_auto_20190427_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruberpriceitem',
            old_name='ruber_prrice',
            new_name='ruber_price',
        ),
    ]
